title: Tianqi Wang's Homepage
page-top-title: Tianqi Wang
top-section-bg-text: Welcome to my personal homepage!
home-subtitle: Tianqi Wang
copyright-text: '&copy; Tianqi Wang 2024-2025. All Rights Reserved.'
